### ISSUE TITLE
Implement GitHub Actions script to run tests.

### ISSUE THREAD

**Issue by oleksandr-jr** [JR-Abstract/reddit-clone-abstract#10]
## Description
As a team lead, I want GitHub action to be implemented.

The action (Pipeline) should run tests and show results.
The pipeline should be triggered on every push to GitHub, for all branches.

To make that happen, we need the [maven-surefire-plugin](https://maven.apache.org/surefire/maven-surefire-plugin/usage.html) and `YAML` config for GitHub Action.

## Additional info
Here is an example:
https://gist.github.com/oleksandr-jr/021d601c49fa46064eed98a021c8a362

https://medium.com/@alexander.volminger/ci-cd-for-java-maven-using-github-actions-d009a7cb4b8f

## Related to
#24 

## Acceptance criteria
> - AK1: Maven-surefire-plugin is configured.
> - AK2: GitHub Action is configured to run tests.
> - AK3: GitHub Action is triggered on every push to GitHub, for all branches

**Comment by oleksandr-jr** [comment]
@ViktorKapustianyk  Returned to ready due to requested fixes.

**Comment by oleksandr-jr** [comment]
@ViktorKapustianyk change was requested [here](https://github.com/JR-Abstract/reddit-clone-abstract/pull/41#discussion_r1507390553)

**Comment by oleksandr-jr** [comment]
@ViktorKapustianyk I see two brunches, which brunch is the right one and which brunch may I remove?

https://github.com/JR-Abstract/reddit-clone-abstract/tree/10-implement-github-actions-script-to-run-tests

https://github.com/JR-Abstract/reddit-clone-abstract/tree/10-implement-github-actions-script-to-run-test

**Comment by ViktorKapustianyk** [comment]
this branch is the right one - https://github.com/JR-Abstract/reddit-clone-abstract/tree/10-implement-github-actions-script-to-run-tests 
and this branch you can remove - https://github.com/JR-Abstract/reddit-clone-abstract/tree/10-implement-github-actions-script-to-run-test

**Comment by oleksandr-jr** [comment]
https://github.com/JR-Abstract/reddit-clone-abstract/pull/42 Is closed and the brunch is removed as well
