### ISSUE TITLE
Weekly deployment

### ISSUE THREAD

**Issue by oleksandr-jr** [JR-Abstract/reddit-clone-abstract#14]
- Merge all the tickets with status `done`
- Test the functionality
- Fix problems / Create issues

**Comment by Y-Maxym** [comment]
[reddit-clone.postman_collection.json](https://github.com/JR-Abstract/reddit-clone-abstract/files/14448044/reddit-clone.postman_collection.json)

**Comment by oleksandr-jr** [comment]
> [reddit-clone.postman_collection.json](https://github.com/JR-Abstract/reddit-clone-abstract/files/14448044/reddit-clone.postman_collection.json)

Nice, I'll create a public collection from it and share it with the team

**Comment by oleksandr-jr** [comment]
@OnDecember https://www.postman.com/jr-abstract/workspace/abstract-reddit could you please test if you have a permission to work with this workspace (Modify it)? You need to have an account

**Comment by Y-Maxym** [comment]
> @OnDecember https://www.postman.com/jr-abstract/workspace/abstract-reddit could you please test if you have a permission to work with this workspace (Modify it)? You need to have an account

@oleksandr-jr Yes, i have permission

**Comment by oleksandr-jr** [comment]
https://github.com/JR-Abstract/reddit-clone-abstract/releases/tag/1.0.0-alpha.1
