### ISSUE TITLE
Add SL4J Logger

### ISSUE THREAD

**Issue by oleksandr-jr** [JR-Abstract/reddit-clone-abstract#15]
https://www.baeldung.com/spring-boot-logging

## AC

1. Logger is configured as RollingFile
2. Size 10Mb
3. Level `WARN` is configured

**Comment by Y-Maxym** [comment]
https://github.com/spring-projects/spring-boot/tree/main/spring-boot-project/spring-boot/src/main/resources/org/springframework/boot/logging/logback
default templates for spring logger
