### ISSUE TITLE
Add PostgreSQL Testcontainers (old task name - H2 database for tests)

### ISSUE THREAD

**Issue by oleksandr-jr** [JR-Abstract/reddit-clone-abstract#24]
## Description
Add H2 database for tests. 
https://www.baeldung.com/spring-testing-separate-data-source

## Related to
#10 

https://www.baeldung.com/spring-boot-testcontainers-integration-test

https://docs.spring.io/spring-boot/docs/current/reference/htmlsingle/#features.testing.testcontainers

## AC

1. The H2 database works with tests.

**Comment by oleksandr-jr** [comment]
@AndriiChipets-Java Hello! What is the status here? Do you need any hint/help to accomplish this task?

**Comment by AndriiChipets-Java** [comment]
@oleksandr-jr Hello! The task is in progress. I've collected information to implement it. I'm going to accomplish that today.  If it fails I'll give you a response tomorrow morning or will move it to review.

**Comment by oleksandr-jr** [comment]
@AndriiChipets-Java Good to know!
Take your time. In the case you need more time, we can easily transfer this task to the next sprint.

**Comment by AndriiChipets-Java** [comment]
@oleksandr-jr Glad to know that. 
Thank you for the information and support)

**Comment by AndriiChipets-Java** [comment]
@oleksandr-jr Hello!
I would like to move this task to the next sprint.
I hope this won't influence too much on the total project flow.
Thank you.

**Comment by AndriiChipets-Java** [comment]
Important! To use testcontainer you need your Docker being run

Added two tests for UserRepository class.


![Image](https://github.com/JR-Abstract/reddit-clone-abstract/assets/132684530/d19627d9-596f-4edd-8227-87d69ff46e53)

Also added schema.sql file with all db tables and dataUser.sql file with data to test UserRepository class.
to test other classes programmer have to create data* file with test data for their tested class, e.g. dataPost.sql for class PostRepository and specify this sql file in Test class, e.g.
@Sql(
        scripts = {
                "/sql/schema.sql",
                "/sql/dataPost.sql"},
        executionPhase = Sql.ExecutionPhase.BEFORE_TEST_METHOD
)


![Image](https://github.com/JR-Abstract/reddit-clone-abstract/assets/132684530/8a12d879-6c5a-4137-9302-a5a1018942d5)

To create test class to use testcontainer you can copy and modify UserRepositoryTest class
