### ISSUE TITLE
UserId is ignored in the mapping logic.

### ISSUE THREAD

**Issue by oleksandr-jr** [JR-Abstract/reddit-clone-abstract#55]
Currently when you create a post user Id is ignored and not stored in the database.

![Image](https://github.com/JR-Abstract/reddit-clone-abstract/assets/116897595/66b02e7b-bcc9-46ef-9d3e-0444aced1b4f)

Take a look at the code:
https://github.com/JR-Abstract/reddit-clone-abstract/commit/8bdab5845daf885838f5d2ab58bf8b165fcf8c7f#diff-04a2272ac2a6522d31ef3fabd566c6ecfebaea2a5fd15fca710aec66f4ecdaa7R12

## AC

1. User id is mapped correctly
2. User id is stored in the database after creating a Post

**Comment by Y-Maxym** [comment]
@oleksandr-jr Is this a bug in the user or post mapper?

**Comment by aleos-dev** [comment]
@oleksandr-jr I don't know how to reproduce the bug. Moreover, I can't understand how it's even possible, as we have proper constraints on the user field.

![Image](https://github.com/JR-Abstract/reddit-clone-abstract/assets/121808229/577e4b3c-830a-4f4e-9eef-4ec30f2a87a3)

**Comment by oleksandr-jr** [comment]
@aleos-dev Tested on integration again and it works fine now :)
Maybe it was some local issue on my setup.
