### ISSUE TITLE
Subreddit creation DTO replace username by user id.

### ISSUE THREAD

**Issue by oleksandr-jr** [JR-Abstract/reddit-clone-abstract#73]
Replace the username by user ID here:

https://github.com/JR-Abstract/reddit-clone-abstract/commit/39ce99483128eef82dac0e34b78c74a8023744cb#diff-4c54172a16628cfd3eba53ea3a875b02d83df9fcd1461bfe76b82f8fc6639bd8R20-R22

## AC

1. Username field is replaced by user id.
2. Mappers are adapted if needed.
3. Tests are adapted if needed.
4. The Functionality is tested.
5. Postman collection requests are changed to corresponds to new DTO's.

**Comment by OnDecember** [comment]
@oleksandr-jr Maybe we can do it through Spring Context so as not to manually substitute the id?
