### ISSUE TITLE
Implement Handling Exception for User Entity

### ISSUE THREAD

**Issue by Y-Maxym** [JR-Abstract/reddit-clone-abstract#75]
## Description

Add exception handling using ExceptionHandler annotation.

## Dependencies

- Implement after #54 is merged.
- Implement after or both #58.

**Comment by Y-Maxym** [comment]
Please open pull request @oleksandrhavryush

**Comment by oleksandrhavryush** [comment]
@Y-Maxym Do you mean I have to create it? I just forgot the sequence of actions a bit. Do I understand correctly that after completing the task, I have to merge in the Integration branch and make a pull requests, and then unassigned and move the task to the ready for review position?

**Comment by Y-Maxym** [comment]
> @Y-Maxym Do you mean I have to create it? I just forgot the sequence of actions a bit. Do I understand correctly that after completing the task, I have to merge in the Integration branch and make a pull requests, and then unassigned and move the task to the ready for review position?

Yeah, that's right.
